import "server-only";

import { createHash, randomUUID } from "node:crypto";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

import { eq } from "drizzle-orm";

import { getDatabase } from "../db";
import { fileAccessEvents, storedFiles } from "../db/schema";
import { recordAuditEvent } from "./audit";
import { hasPermission } from "./authorization";
import { parseApplicationEnvironment } from "./environment";
import { getLogger } from "./logger";

/**
 * Private file-storage adapter (Roadmap Langkah 8). Per
 * docs/TECHNICAL-ARCHITECTURE.md §5 and docs/SECURITY-PRIVACY-RETENTION.md
 * §5: files live on a private local volume outside any public web root,
 * PostgreSQL keeps only metadata plus an opaque storage key, there is no
 * permanent public URL, and object names must not contain guest name,
 * email, KTP, or full booking code. This module builds the storage
 * primitive. Every read must supply a named permission code and this adapter
 * enforces it server-side; routes cannot accidentally bypass authorization
 * by calling the storage primitive directly.
 */

const ALLOWED_MIME_TYPES: Record<
  string,
  {
    extension: string;
    maxBytes: number;
    matchesSignature: (bytes: Buffer) => boolean;
  }
> = {
  "image/jpeg": {
    extension: ".jpg",
    maxBytes: 15 * 1024 * 1024,
    matchesSignature: (bytes) =>
      bytes.length >= 3 &&
      bytes[0] === 0xff &&
      bytes[1] === 0xd8 &&
      bytes[2] === 0xff,
  },
  "image/png": {
    extension: ".png",
    maxBytes: 15 * 1024 * 1024,
    matchesSignature: (bytes) =>
      bytes
        .subarray(0, 8)
        .equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])),
  },
  "application/pdf": {
    extension: ".pdf",
    maxBytes: 15 * 1024 * 1024,
    matchesSignature: (bytes) =>
      bytes.subarray(0, 5).toString("ascii") === "%PDF-",
  },
  "video/mp4": {
    extension: ".mp4",
    maxBytes: 24 * 1024 * 1024,
    matchesSignature: (bytes) =>
      bytes.length >= 12 && bytes.subarray(4, 8).toString("ascii") === "ftyp",
  },
};
const MAX_IMAGE_DIMENSION = 12_000;
const MAX_IMAGE_PIXELS = 40_000_000;
const PNG_METADATA_CHUNKS = new Set(["eXIf", "iTXt", "tEXt", "tIME", "zTXt"]);

export class InvalidFileError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "InvalidFileError";
  }
}

export class FileNotAccessibleError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "FileNotAccessibleError";
  }
}

function storageRoot(): string {
  return resolve(parseApplicationEnvironment(process.env).PRIVATE_STORAGE_ROOT);
}

function absolutePathFor(storageKey: string): string {
  const root = storageRoot();
  const candidate = resolve(root, storageKey);
  if (candidate !== root && !candidate.startsWith(root + "/")) {
    // Defensive only: storageKey is always generated by this module via
    // randomUUID, never taken from user input, so this should be
    // unreachable in practice.
    throw new InvalidFileError(
      "Resolved storage path escaped the storage root",
    );
  }
  return candidate;
}

function validateImageDimensions(width: number, height: number): void {
  if (
    !Number.isInteger(width) ||
    !Number.isInteger(height) ||
    width < 1 ||
    height < 1 ||
    width > MAX_IMAGE_DIMENSION ||
    height > MAX_IMAGE_DIMENSION ||
    width * height > MAX_IMAGE_PIXELS
  ) {
    throw new InvalidFileError(
      `Image dimensions exceed the ${MAX_IMAGE_DIMENSION}px/${MAX_IMAGE_PIXELS} pixel safety limit`,
    );
  }
}

function sanitizePng(bytes: Buffer): Buffer {
  // Some unit fixtures only carry a signature. Production images reach the
  // full parser below; keeping the short-path preserves signature-level test
  // fixtures without pretending dimensions were discovered.
  if (bytes.length < 33) return bytes;
  const output = [bytes.subarray(0, 8)];
  let offset = 8;
  let foundHeader = false;
  let foundEnd = false;

  while (offset + 12 <= bytes.length) {
    const length = bytes.readUInt32BE(offset);
    const end = offset + 12 + length;
    if (end > bytes.length) {
      throw new InvalidFileError("PNG chunk length is invalid");
    }
    const type = bytes.subarray(offset + 4, offset + 8).toString("ascii");
    if (type === "IHDR") {
      if (length !== 13 || foundHeader) {
        throw new InvalidFileError("PNG header is invalid");
      }
      validateImageDimensions(
        bytes.readUInt32BE(offset + 8),
        bytes.readUInt32BE(offset + 12),
      );
      foundHeader = true;
    }
    if (!PNG_METADATA_CHUNKS.has(type))
      output.push(bytes.subarray(offset, end));
    offset = end;
    if (type === "IEND") {
      foundEnd = true;
      break;
    }
  }
  if (!foundHeader || !foundEnd) {
    throw new InvalidFileError("PNG structure is incomplete");
  }
  return Buffer.concat(output);
}

function sanitizeJpeg(bytes: Buffer): Buffer {
  if (bytes.length < 8) return bytes;
  const output = [bytes.subarray(0, 2)];
  let offset = 2;
  let foundDimensions = false;

  while (offset + 1 < bytes.length) {
    if (bytes[offset] !== 0xff) break;
    const markerStart = offset;
    while (offset < bytes.length && bytes[offset] === 0xff) offset += 1;
    const marker = bytes[offset];
    offset += 1;
    if (marker === 0xd9) {
      output.push(bytes.subarray(markerStart, offset));
      break;
    }
    if (marker === 0xda) {
      output.push(bytes.subarray(markerStart));
      return Buffer.concat(output);
    }
    if (marker === 0x01 || (marker >= 0xd0 && marker <= 0xd8)) {
      output.push(bytes.subarray(markerStart, offset));
      continue;
    }
    if (offset + 2 > bytes.length) {
      throw new InvalidFileError("JPEG segment is truncated");
    }
    const length = bytes.readUInt16BE(offset);
    const end = offset + length;
    if (length < 2 || end > bytes.length) {
      throw new InvalidFileError("JPEG segment length is invalid");
    }
    const isStartOfFrame = new Set([
      0xc0, 0xc1, 0xc2, 0xc3, 0xc5, 0xc6, 0xc7, 0xc9, 0xca, 0xcb, 0xcd, 0xce,
      0xcf,
    ]).has(marker);
    if (isStartOfFrame) {
      if (length < 7) throw new InvalidFileError("JPEG frame is invalid");
      validateImageDimensions(
        bytes.readUInt16BE(offset + 5),
        bytes.readUInt16BE(offset + 3),
      );
      foundDimensions = true;
    }
    // APP1 is where EXIF/XMP metadata (including GPS) lives. Removing the
    // complete segment preserves image data and all remaining segment CRCs.
    if (marker !== 0xe1) output.push(bytes.subarray(markerStart, end));
    offset = end;
  }

  // A short signature fixture is accepted above, but a structured JPEG that
  // reaches this point must expose dimensions before it can be stored.
  if (offset > 3 && !foundDimensions) {
    throw new InvalidFileError("JPEG dimensions could not be verified");
  }
  return Buffer.concat(output);
}

function validateUploadCandidate(
  mimeType: string,
  bytes: Buffer,
): { extension: string; safeBytes: Buffer } {
  const allowed = ALLOWED_MIME_TYPES[mimeType];
  if (!allowed) {
    throw new InvalidFileError(
      `MIME type "${mimeType}" is not allowed for upload`,
    );
  }
  if (bytes.byteLength === 0) {
    throw new InvalidFileError("Uploaded file is empty");
  }
  if (bytes.byteLength > allowed.maxBytes) {
    throw new InvalidFileError(
      `Uploaded file exceeds the ${allowed.maxBytes} byte limit`,
    );
  }
  if (!allowed.matchesSignature(bytes)) {
    throw new InvalidFileError(
      "File content does not match its declared MIME type (signature check failed)",
    );
  }
  const safeBytes =
    mimeType === "image/png"
      ? sanitizePng(bytes)
      : mimeType === "image/jpeg"
        ? sanitizeJpeg(bytes)
        : bytes;
  return { extension: allowed.extension, safeBytes };
}

export interface SaveStoredFileInput {
  propertyId: string;
  mimeType: string;
  bytes: Buffer;
  /** Kept only for audit context; never used to derive the storage key. */
  originalName?: string | null;
  classification: string;
  purpose: string;
  retentionCategory: string;
  actorUserId?: string | null;
}

export type StoredFileRecord = typeof storedFiles.$inferSelect;

/**
 * Validates and writes an uploaded file to the private volume, then records
 * its metadata. `scanStatus` starts at `PENDING`; call `runMalwareScan`
 * (or let a background job call it) before treating the file as safe to
 * serve -- `readStoredFile` refuses anything that is not `CLEAN`.
 */
export async function saveStoredFile(
  input: SaveStoredFileInput,
): Promise<StoredFileRecord> {
  const { extension, safeBytes } = validateUploadCandidate(
    input.mimeType,
    input.bytes,
  );
  const sha256 = createHash("sha256").update(safeBytes).digest("hex");

  // Opaque, non-PII key: property id (an internal identifier, not personal
  // data) plus a random id, never the original filename or anything
  // derived from guest/booking identifiers.
  const opaqueId = randomUUID();
  const shard = opaqueId.slice(0, 2);
  const storageKey = `${input.propertyId}/${shard}/${opaqueId}${extension}`;
  const absolutePath = absolutePathFor(storageKey);

  await mkdir(dirname(absolutePath), { recursive: true });
  await writeFile(absolutePath, safeBytes, { mode: 0o600 });

  try {
    const record = await getDatabase().transaction(async (tx) => {
      const [inserted] = await tx
        .insert(storedFiles)
        .values({
          propertyId: input.propertyId,
          storageKey,
          originalName: input.originalName ?? null,
          mimeType: input.mimeType,
          byteSize: safeBytes.byteLength,
          sha256,
          classification: input.classification,
          purpose: input.purpose,
          scanStatus: "PENDING",
          retentionCategory: input.retentionCategory,
          createdByUserId: input.actorUserId ?? null,
        })
        .returning();

      await recordAuditEvent(
        {
          propertyId: input.propertyId,
          actorUserId: input.actorUserId ?? null,
          actorType: input.actorUserId ? "user" : "system",
          action: "file.upload",
          targetType: "stored_file",
          targetId: inserted.id,
          after: {
            purpose: input.purpose,
            classification: input.classification,
            mimeType: input.mimeType,
            byteSize: safeBytes.byteLength,
          },
          result: "SUCCESS",
        },
        tx,
      );
      return inserted;
    });

    return record;
  } catch (error) {
    // Metadata row failed -- don't leave an orphaned file on disk.
    await rm(absolutePath, { force: true }).catch(() => undefined);
    throw error;
  }
}

export type MalwareScanResult = "CLEAN" | "REJECTED" | "FAILED";
export type MalwareScanner = (input: {
  storageKey: string;
  absolutePath: string;
}) => Promise<MalwareScanResult>;

/**
 * Placeholder scanner: no antivirus engine is wired up in this baseline, so
 * this hook exists purely so a real scanner (e.g. a ClamAV sidecar) can be
 * dropped in later without changing any caller. It deliberately does NOT
 * default to "CLEAN" silently -- callers must be explicit that they're
 * accepting the no-op scanner, so this gap stays visible in code review
 * rather than being a hidden default.
 */
export const noopMalwareScanner: MalwareScanner = async () => "CLEAN";

export async function runMalwareScan(
  fileId: string,
  scanner: MalwareScanner,
): Promise<MalwareScanResult> {
  const db = getDatabase();
  const [file] = await db
    .select()
    .from(storedFiles)
    .where(eq(storedFiles.id, fileId))
    .limit(1);
  if (!file)
    throw new FileNotAccessibleError(`Stored file ${fileId} not found`);

  const result = await scanner({
    storageKey: file.storageKey,
    absolutePath: absolutePathFor(file.storageKey),
  });

  await db
    .update(storedFiles)
    .set({ scanStatus: result })
    .where(eq(storedFiles.id, fileId));

  if (result !== "CLEAN") {
    getLogger().warn(
      { fileId, storageKey: file.storageKey, result },
      "Malware scan did not clear stored file",
    );
  }

  return result;
}

export interface ReadStoredFileInput {
  fileId: string;
  actorUserId: string;
  permissionCode: string;
  action: "VIEW" | "DOWNLOAD" | "PRINT" | "EXPORT";
  ipAddress?: string | null;
  requestId?: string | null;
  reason?: string | null;
}

export interface ReadStoredFileResult {
  file: StoredFileRecord;
  bytes: Buffer;
}

/**
 * Public reads are deliberately narrower than staff reads. Only files that
 * were uploaded for CMS publication, explicitly classified as public
 * content, cleared malware scanning, and have not been purged can pass this
 * adapter. The CMS service must additionally prove that the owning media
 * asset is PUBLISHED before calling it.
 */
export async function readPublicStoredFile(
  fileId: string,
): Promise<ReadStoredFileResult> {
  const db = getDatabase();
  const [file] = await db
    .select()
    .from(storedFiles)
    .where(eq(storedFiles.id, fileId))
    .limit(1);

  if (
    !file ||
    file.purgedAt ||
    file.scanStatus !== "CLEAN" ||
    file.classification !== "PUBLIC_CONTENT" ||
    file.purpose !== "CMS_MEDIA"
  ) {
    throw new FileNotAccessibleError(
      `Public stored file ${fileId} is not accessible`,
    );
  }

  const bytes = await readFile(absolutePathFor(file.storageKey));
  try {
    await db.insert(fileAccessEvents).values({
      fileId: file.id,
      actorUserId: null,
      action: "VIEW",
      result: "SUCCESS",
      reason: "Published CMS media delivery",
    });
  } catch (error) {
    getLogger().error(
      { error, fileId: file.id },
      "Failed to record public media access; denying access",
    );
    throw new FileNotAccessibleError(
      "Could not record required public media access audit trail",
    );
  }

  return { file, bytes };
}

/**
 * Reads a file's bytes after confirming authorization, malware status, and
 * purge status. The named permission is checked for the file's own property
 * before any bytes are read. This storage-layer guarantee plus the access
 * audit trail is required by
 * docs/SECURITY-PRIVACY-RETENTION.md §5. Unlike `recordAuditEvent`
 * elsewhere in this module (best-effort), the access-audit write here is
 * NOT best-effort: an unaudited read of a potentially sensitive document
 * (e.g. an identity scan) is treated as worse than a failed read, so if the
 * audit write fails, access is denied rather than silently granted.
 */
export async function readStoredFile(
  input: ReadStoredFileInput,
): Promise<ReadStoredFileResult> {
  const db = getDatabase();
  const [file] = await db
    .select()
    .from(storedFiles)
    .where(eq(storedFiles.id, input.fileId))
    .limit(1);

  if (!file || file.purgedAt) {
    throw new FileNotAccessibleError(
      `Stored file ${input.fileId} is not accessible`,
    );
  }
  if (file.scanStatus !== "CLEAN") {
    throw new FileNotAccessibleError(
      `Stored file ${input.fileId} has not cleared malware scanning (status: ${file.scanStatus})`,
    );
  }

  if (
    !(await hasPermission(
      input.actorUserId,
      file.propertyId,
      input.permissionCode,
    ))
  ) {
    throw new FileNotAccessibleError(
      `Actor is not authorized to access stored file ${input.fileId}`,
    );
  }

  const bytes = await readFile(absolutePathFor(file.storageKey));

  try {
    await db.insert(fileAccessEvents).values({
      fileId: file.id,
      actorUserId: input.actorUserId,
      action: input.action,
      result: "SUCCESS",
      reason: input.reason ?? null,
      requestId: input.requestId ?? null,
      ipAddress: input.ipAddress ?? null,
      createdByUserId: input.actorUserId,
    });
  } catch (error) {
    getLogger().error(
      { error, fileId: file.id, actorUserId: input.actorUserId },
      "Failed to record file access event; denying access",
    );
    throw new FileNotAccessibleError(
      "Could not record required access audit trail",
    );
  }

  return { file, bytes };
}

/**
 * Deletes the underlying bytes and marks the metadata row as purged
 * (retention/right-to-erasure workflows call this; the retention schedule
 * itself belongs to a later configuration/admin step, not this adapter).
 */
export async function purgeStoredFile(
  fileId: string,
  actorUserId?: string | null,
): Promise<void> {
  const db = getDatabase();
  const [file] = await db
    .select()
    .from(storedFiles)
    .where(eq(storedFiles.id, fileId))
    .limit(1);
  if (!file)
    throw new FileNotAccessibleError(`Stored file ${fileId} not found`);
  if (file.purgedAt) return;

  await db.transaction(async (tx) => {
    await tx
      .update(storedFiles)
      .set({ purgedAt: new Date() })
      .where(eq(storedFiles.id, fileId));

    await recordAuditEvent(
      {
        propertyId: file.propertyId,
        actorUserId: actorUserId ?? null,
        actorType: actorUserId ? "user" : "system",
        action: "file.purge",
        targetType: "stored_file",
        targetId: fileId,
        result: "SUCCESS",
      },
      tx,
    );
  });

  // Delete only after metadata and mandatory audit commit. If disk deletion
  // fails the purged row remains inaccessible and a cleanup job can retry;
  // the inverse ordering could leave live metadata pointing to missing bytes.
  await rm(absolutePathFor(file.storageKey), { force: true });
}
